---
version: '3'

services:
    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_backups:/backups
        expose:
            - 5432
        env_file:
            - .env.deploy

    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        command: start_gunicorn
        volumes:
            - app_static:/application/static
        expose:
            - 8000
        env_file:
            - .env.deploy
        depends_on:
            - postgres

    nginx:
        build: ./docker/nginx
        volumes:
            - app_static:/application/static
        ports:
            - 1337:80
        depends_on:
            - app

volumes:
    app_static:
    postgres_data:
    postgres_backups:
